name: chocolatine

on:
  push:
    branches-ignore:
      - 'no-ga/**'
  pull_request:
    branches-ignore:
      - 'no-ga/**'

env:
  MIRROR_SSH_URL: ""
  EXECUTABLES: ""

jobs:
  check_compilation_and_coding_style:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - run: banana-check-repo .
      - run: CC=epiclang make
        timeout-minutes: 2
      - run: make clean
      - run: |
          IFS=',' read -ra ADDR <<< "$EXECUTABLES"
          for i in "${ADDR[@]}"; do
            if [ ! -x "$i" ]; then
              echo "::error file=$i::Executable not found or not executable"
              exit 1
            fi
          done

  run_tests:
    needs: check_compilation_and_coding_style
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    needs: run_tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_SSH_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
